version: "3"
services:
    postgres-db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
    api:
        depends_on:
            - postgres-db
        image: anuppal17/simple-blog-api
        ports:
          - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=postgres-db
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432